### ISSUE TITLE
Add Me.

### ISSUE THREAD

**Issue by NFGamerMC** [RockySoftware/Rocky#1]
Can you please add me?

**Comment by caspervanneck** [comment]
if going to kick some one not

**Comment by NFGamerMC** [comment]
I just need to kick @XxParkerGamesxX. I founded this anyways. You are being like Linux now

**Comment by caspervanneck** [comment]
okey

**Comment by caspervanneck** [comment]
i have at you ):

**Comment by NFGamerMC** [comment]
Add me to ImagicalMine reactive so I can remove him for illegal copyright

**Comment by caspervanneck** [comment]
@NFGamerMC its not my i cant

**Comment by NFGamerMC** [comment]
Are you an owner?

**Comment by caspervanneck** [comment]
nope a member

**Comment by NFGamerMC** [comment]
@caspervanneck Accept This (it killed the Server) https://github.com/ImagicalMineReactive/ImagicalMine/pull/20

**Comment by caspervanneck** [comment]
lel

**Comment by NFGamerMC** [comment]
Accept this now, (it is my dummy account) https://github.com/ImagicalMineReactive/ImagicalMine/pull/21
