### ISSUE TITLE
Please add more items and blocks.

### ISSUE THREAD

**Issue by shdudwns** [RockySoftware/Rocky#12]
Why are blocks and items missing?

**Comment by Fabiansigala** [comment]
@shdudwns please explane what items and blocks

**Comment by shdudwns** [comment]
Please add a signal. And let me use endeojin.
@Fabiansigala

**Comment by Fabiansigala** [comment]
@shsdwns ?

**Comment by Fabiansigala** [comment]
@shdudwns ?
