### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [RockySoftware/Rocky#5]
root@localhost pmmp]# ./st*
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory
[CRITICAL] Unable to find the PocketMine-SPL library.
[CRITICAL] Please use provided builds or clone the repository recursively.
[root@localhost pmmp]#

**Comment by caspervanneck** [comment]
use phar not src

**Comment by jdongel2004** [comment]
@shdudwns doesn't know how he can get .phar file.

**Comment by caspervanneck** [comment]
@shdudwns here the link https://25-91155606-gh.circle-artifacts.com/0/tmp/circle-artifacts.5E6WEfo/Rocky_1.0.2.phar

**Comment by shdudwns** [comment]
@caspervanneck How do I make a phar?

**Comment by caspervanneck** [comment]
@shdudwns download from that link

**Comment by NFGamerMC** [comment]
You do not need a phar, just sync the sub modules

**Comment by shdudwns** [comment]
Then https://25-91155606-gh.circle-artifacts.com/0/tmp/circle-artifacts.5E6WEfo/Rocky_1.0.2.phar Can you always download the latest version of this site?
