### ISSUE TITLE
HELP?

### ISSUE THREAD

**Issue by MinecraftPlayz** [RockySoftware/Rocky#7]
@caspervanneck @BlawoHD @XxParkerGamesxX @Fabiansigala Can I please help? I am great at PHP and have completed the course. I am also great at using the API.

**Comment by XxParkerGamesxX** [comment]
Ill have the boys decide this one

**Comment by Fabiansigala** [comment]
@XxParkerGamesxX lol

**Comment by Fabiansigala** [comment]
Hmm should we? @caspervanneck

**Comment by Fabiansigala** [comment]
@MinecraftPlayz we will think about it

**Comment by XxParkerGamesxX** [comment]
Idk i invited him we will see if he does good
I expect good things from you @MinecraftPlayz

**Comment by Fabiansigala** [comment]
@MinecraftPlayz welcome to Rocky

**Comment by caspervanneck** [comment]
if you are nfgamermc i wil kick your bud hole

**Comment by MinecraftPlayz** [comment]
@caspervanneck who is NFGamerMC? Also I am not owner so it won't let me access Travis.

**Comment by MinecraftPlayz** [comment]
Also i don't have write access, so I cannot commit. It says thang it is forking.

**Comment by Fabiansigala** [comment]
@MinecraftPlayz nfgamer is um well.

**Comment by Fabiansigala** [comment]
@MinecraftPlayz is banned...

**Comment by MinecraftPlayz** [comment]
Ohh, also I cannot commit.

**Comment by Fabiansigala** [comment]
@MinecraftPlayz make a pull

**Comment by Fabiansigala** [comment]
@MinecraftPlayz and I will review it and add it

**Comment by MinecraftPlayz** [comment]
How many PR's before I can be granted to make commits without a pr?

**Comment by Fabiansigala** [comment]
@MinecraftPlayz soon but you have to prove.
