### ISSUE TITLE
List All 1.1.0 stuff

### ISSUE THREAD

**Issue by XxParkerGamesxX** [RockySoftware/Rocky#8]
List all blocks and mobs they added into 1.1.0
For i could add them

**Comment by Fabiansigala** [comment]
Ok

**Comment by Fabiansigala** [comment]
Totem

**Comment by Fabiansigala** [comment]
Lol emy email is getting spammed XD

**Comment by XxParkerGamesxX** [comment]
Dont just give me the item give me the ids too

**Comment by Fabiansigala** [comment]
Ok

**Comment by Fabiansigala** [comment]
repeating_command_block         188
chain_command_block             189
Maybe should we add them?

**Comment by Fabiansigala** [comment]
purple_glazed_terracotta        219
white_glazed_terracotta         220
orange_glazed_terracotta        221
magenta_glazed_terracotta       222
light_blue_glazed_terracotta    223
yellow_glazed_terracotta        224
lime_glazed_terracotta          225
pink_glazed_terracotta          226
gray_glazed_terracotta          227
silver_glazed_terracotta        228
cyan_glazed_terracotta          229
blue_glazed_terracotta          231
brown_glazed_terracotta         232
green_glazed_terracotta         233
red_glazed_terracotta           234
black_glazed_terracotta         235
concrete                        236

**Comment by Fabiansigala** [comment]
concretePowder                  237

**Comment by caspervanneck** [comment]
lol

**Comment by Fabiansigala** [comment]
chorus_plant                    240
stained_glass                   241

**Comment by Fabiansigala** [comment]
@XxParkerGamesxX do you want every I'd?

**Comment by XxParkerGamesxX** [comment]
UMM YOU WANT TO CRASH OUR SOFTWARE?
look what you just said

**Comment by Fabiansigala** [comment]
Oops sorry

**Comment by Fabiansigala** [comment]
XD

**Comment by XxParkerGamesxX** [comment]
you said 'StainedGlass'
lol its not even added I wish it was

**Comment by XxParkerGamesxX** [comment]
Like my profile pic

**Comment by XxParkerGamesxX** [comment]
we both have f's

**Comment by Fabiansigala** [comment]
Woof

**Comment by XxParkerGamesxX** [comment]
xd

**Comment by Fabiansigala** [comment]
Lol

**Comment by Fabiansigala** [comment]
@XxParkerGamesxX check discord

**Comment by NFGamerMC** [comment]
@XxParkerGamesxX Nobody likes you.
