### ISSUE TITLE
Server allows you to join but then crashes.

### ISSUE THREAD

**Issue by alexbgameson** [RockySoftware/Rocky#9]
Server allows you to join but then crashes.

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52
[16:00:19] [Server thread/INFO]: cooldudecool[/192.168.1.10:65003] logged in with entity id 1 at (world, 128, 68, 128)

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52
[16:00:19] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\CompressBatchedTask::__construct() must be an instance of pocketmine\network\mcpe\protocol\BatchPacket, string given, called in C:\Users\Alex\Desktop\server82\src\pocketmine\Server.php on line 1982" (EXCEPTION) in "/src/pocketmine/network/CompressBatchedTask" at line 34

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52
[16:00:19] [RakLibServer thread/NOTICE]: Blocked 192.168.1.10 for 5 seconds

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

Warning: assert(): assert($this->compressed) failed in C:\Users\Alex\Desktop\server82\src\pocketmine\network\mcpe\protocol\BatchPacket.php on line 52

**Comment by MinecraftPlayz** [comment]
Are you using a VPN, Pocketmine has good Haker protection. I could fix but it says to PR if I want to commit.

**Comment by alexbgameson** [comment]
No, Im not using a vpn.
